### PR TITLE
modified IRremote to support multiple transmitter pins

### PR DESCRIPTION
**Pull request by khair-eddine**
creating new instance of timer enable and timer disable pwm with different pins( com1B1 for pin 9 and com1A1 for pin 10 of the arduino) 
 #define TIMER_ENABLE_PWM3     (TCCR1A |= _BV(COM1B1))  
# define TIMER_DISABLE_PWM3    (TCCR1A &= ~(_BV(COM1B1)))
# define TIMER_ENABLE_PWM4     (TCCR1A |= _BV(COM1A1))
# define TIMER_DISABLE_PWM4    (TCCR1A &= ~(_BV(COM1A1)))

defining the pwm options using registers of timer1 and timer2 for new pins 
  TCCR1A = _BV(WGM11); \
  TCCR1B = _BV(WGM13) | _BV(CS10); \
  OCR1B = pwmval / 3; \

### CODE REVIEW

**Comment by z3t0** [comment]
@khair-eddine That's a lot of work and will help a lot in the development of the library, I was wondering if there were a more efficient way to do this, like somehow have instances of Irsend and specify the pin, so we could set it up that you could (effectively) have as many as you want without physically replicating the code.

**Comment by khair-eddine** [comment]
well bro, not all pins are PWM in arduino so you can't use any pin that you want, i worked with timer1 and timer2 because they are already defined for pin(9 and 3 and i added pin 10) but to work with timer0 i need a lot of time to get more pins from timer0 and for the efficienty of  the modification i'll try to improve but after finishing some project.

**Comment by khair-eddine** [comment]
@z3t0 you tried it ?

**Comment by z3t0** [comment]
No i havent been able to try it because i no longer have my old board, i will try and solder some headers to a teensy and use that.

--
Thanks,
Rafi Khan 

----- Reply message -----

**Pull request closed without merging**
